project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exerise 1 - A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exerise 2 - Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exerise 3.1 - Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exerise 3.2 - Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exerise 4.1 - Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex401.html"
        - text: "Hands-on Exerise 4.2 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex042.html"
        - text: "Hands-on Exerise 4.3 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex043.html"
        - text: "Hands-on Exerise 4.4 - Hands-on Exercise 4.4 - Funnel Plots for Fair Comparisons"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex044.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:   
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "Home"
        href: "index.qmd"
      - section: "Hands-on Exercise"
        contents:
          - text: "1 - A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "2 - Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "3.1 - Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "3.2 - Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "4.1 - Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex401.html"
          - text: "4.2 - Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex042.html"
          - text: "4.3 - Hands-on Exercise 4.3 - Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex043.html"
          - text: "4.4 - Hands-on Exercise 4.4 - Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex044.html"
      - section: "Take-home Exercise"
        contents:
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

