project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exerise 1 - A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exerise 2 - Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exerise 3.1 - Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exerise 3.2 - Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exerise 4.1 - Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex401.html"
        - text: "Hands-on Exerise 4.2 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex042.html"
        - text: "Hands-on Exerise 4.3 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex043.html"
        - text: "Hands-on Exerise 4.4 - Funnel Plots for Fair Comparisons"
          href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex044.html"
        - text: "Hands-on Exerise 5 - Modelling, Visualising and Analysing Network Data with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exerise 6 - Visualising and Analysing Time-oriented Data"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exerise 8.1 - Choropleth Mapping in R"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex081.html"
        - text: "Hands-on Exerise 8.2 - Visualising Geospatial Point Data"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex082.html"
        - text: "Hands-on Exerise 8.3 - Analytical Mapping"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex083.html"
        - text: "Hands-on Exerise 9.1 - Creating Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex091.html"
        - text: "Hands-on Exerise 9.2 - Visual Correlation Analysis"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex092.html"
        - text: "Hands-on Exerise 9.3 - Heatmap for Visualising and Analysing Multivariate Data"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex093.html"
        - text: "Hands-on Exerise 9.4 - Visual Multivariate Analysis with Parallel Coordinates Plot"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex094.html"
        - text: "Hands-on Exerise 9.5 - Treemap Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex095.html"
        - text: "Hands-on Exerise 10 - Information Dashboard Design: R methods"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1 - Phase 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 1 - Phase 2"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01_Phrase 2.html"
        - text: "Take-home Exercise 2 - VAST Challenge 2025 - Mini Challenge 3"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Exercise 3 - Prototyping Modules for Visual Analytics Shiny Application"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05.html"
        - text: "In-class Exercise 10 - Investment Vis"
          href: "In-class_Ex/In-class_Ex10.html"
    right:   
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "Home"
        href: "index.qmd"
      - section: "Hands-on Exercise"
        contents:
          - text: "1 - A Layered Grammar of Graphics: ggplot2 methods"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "2 - Beyond ggplot2 Fundamentals"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "3.1 - Programming Interactive Data Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "3.2 - Programming Animated Statistical Graphics with R"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "4.1 - Visualising Distribution"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex401.html"
          - text: "4.2 - Visual Statistical Analysis"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex042.html"
          - text: "4.3 - Visualising Uncertainty"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex043.html"
          - text: "4.4 - Funnel Plots for Fair Comparisons"
            href: "Hands-on_Ex/Hands-on_L_Ex04/Hands-on_Ex044.html"
          - text: "5 - Modelling, Visualising and Analysing Network Data with R"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "6 - Visualising and Analysing Time-oriented Data"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "8.1 - Choropleth Mapping in R"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex081.html"
          - text: "8.2 - Visualising Geospatial Point Data"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex082.html"
          - text: "8.3 - Analytical Mapping"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex083.html"
          - text: "9.1 - Creating Ternary Plot with R"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex091.html"
          - text: "9.2 - Visual Correlation Analysis"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex092.html"
          - text: "9.3 - Heatmap for Visualising and Analysing Multivariate Data"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex093.html"
          - text: "9.4 - Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex094.html"
          - text: "9.5 - Treemap Visualisation with R"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex095.html"
          - text: "10 - Information Dashboard Design: R methods"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - section: "Take-home Exercise"
        contents:
          - text: "Take-home Exercise 1 - Phase 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 1 - Phase 2"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01_Phrase 2.html"
          - text: "Take-home Exercise 2 - VAST Challenge 2025 - Mini Challenge 3"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3 - Prototyping Modules for Visual Analytics Shiny Application"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - section: "In-class Exercise"
        contents:
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05.html"
          - text: "In-class Exercise 10 - Investment Vis"
            href: "In-class_Ex/In-class_Ex10.html"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

